# แบบที่ 1

In [1]:
import pandas as pd

In [2]:
url = 'https://www.settrade.com/C13_MarketSummary.jsp?detail=SET50'

In [3]:
df = pd.read_html(url)

In [4]:
len(df)

6

In [5]:
df

[  Unnamed: 0   ล่าสุด  เปลี่ยน  แปลง  %เปลี่ยน  แปลง   สูงสุด   ต่ำสุด  \
 0        SET  1482.38          -1.51           -0.10  1489.78  1475.01
 1      SET50   947.28          -1.71           -0.18   953.60   940.86
 2     SET100  2116.85          -3.39           -0.16  2130.57  2103.80
 3       sSET   721.04          -1.61           -0.22   726.51   720.68
 4    SETCLMV   970.42          -6.03           -0.62   979.68   965.81
 5      SETHD  1050.40          -4.11           -0.39  1058.45  1042.83
 6    SETTHSI   929.59          -1.45           -0.16   933.75   923.17
 7      SETWB   911.12          -3.52           -0.38   919.17   905.25
 8        mai   338.57           1.29            0.38   340.26   337.76

    ปริมาณ  ('000 หุ้น)  มูลค่า  (ล้านบาท)
 0             23061923          117095.61
 1              3289303           77714.93
 2              5131122           92684.61
 3               817414            3582.92
 4              2134929           56058.29
 5               961085           25229.81
 6              3109019           58681.32
 7               862004           35821.50
 8              1139986            1868.10  ,
        Unnamed: 0 หลักทรัพย์ * ปริมาณ  *('000 หุ้น)
 0       เพิ่มขึ้น          636              6495512
 1  ไม่เปลี่ยนแปลง          443              5009461
 2            ลดลง         1130             12179186
 3       สถานะตลาด       Closed               Closed,
               ค่าสถิติสำคัญและผลการดำเนินงาน
                           Unnamed: 0_level_1       SET     mai
 0  มูลค่าหลักทรัพย์ตามราคาตลาด. (พันล้านบาท)  16368.35  242.04
 1    อันตราหมุนเวียนปริมาณการซื้อขาย(YTD)(%)    212.28   56.32
 2                                 P/E (เท่า)     29.42   71.81
 3                                P/BV (เท่า)      1.67    1.77
 4                    อัตราเงินปันผลตอบแทน(%)      3.26    2.49,
    หลักทรัพย์    เปิด  สูงสุด  ต่ำสุด  ล่าสุด  เปลี่ยนแปลง  %เปลี่ยนแปลง  \
 0      ADVANC  189.50  190.50  187.00  187.50        -1.50         -0.79
 1         AOT   66.00   66.25   65.00   65.00        -1.00         -1.52
 2         AWC    5.10    5.15    5.00    5.10         0.00          0.00
 3         BBL  127.50  128.00  124.00  125.00        -3.50         -2.72
 4        BDMS   22.00   22.20   21.70   21.80        -0.30         -1.36
 5         BEM    9.05    9.10    9.00    9.10         0.05          0.55
 6       BGRIM   52.00   52.00   50.50   51.25        -0.75         -1.44
 7          BH  121.50  123.00  119.50  120.00        -2.50         -2.04
 8         BJC   37.50   37.75   36.75   37.50         0.00          0.00
 9         BPP   17.10   17.50   17.10   17.10        -0.10         -0.58
 10        BTS   10.40   10.50   10.20   10.50         0.20          1.94
 11        CBG  115.00  115.00  112.50  114.00        -0.50         -0.44
 12      CPALL   62.75   63.00   61.50   62.00        -0.50         -0.80
 13        CPF   27.25   27.75   26.75   27.50         0.00          0.00
 14        CPN   53.00   53.75   52.50   53.25        -0.25         -0.47
 15        CRC   34.75   35.25   34.25   35.25         0.50          1.44
 16       DTAC   36.00   36.50   34.75   35.25        -1.00         -2.76
 17         EA   45.75   47.25   45.75   47.00         1.25          2.73
 18       EGCO  210.00  211.00  204.00  206.00        -4.00         -1.90
 19     GLOBAL   18.40   18.60   18.20   18.40         0.00          0.00
 20       GPSC   70.50   71.00   69.50   70.50        -0.25         -0.35
 21       GULF   35.50   35.75   35.00   35.75         0.25          0.70
 22      HMPRO   14.30   14.60   14.30   14.50         0.20          1.40
 23     INTUCH   58.25   58.25   57.25   57.50        -0.50         -0.86
 24       IRPC    3.84    3.86    3.70    3.78        -0.06         -1.56
 25        IVL   36.50   37.75   36.00   37.75         1.00          2.72
 26      KBANK  120.00  121.00  118.50  119.00        -2.50         -2.06
 27        KTB   11.80   11.90   11.60   11.80        -0.10         -0.84
 28        KTC   55.00   56.00   54.50   55.75         1.00          1.83
 29         LH    8.45    8.65    8.45    8.65         0.15          1.76
 30       MINT   27.50   27.75   26.75   26.75        -0.75         -2.73
 31        MTC   57.50   60.00   57.00   59.75         2.50          4.37
 32        OSP   38.00   38.75   37.50   38.00         0.00          0.00
 33        PTT   42.75   43.25   42.50   42.75         0.50          1.18
 34      PTTEP  101.50  102.50  100.00  100.50        -1.50         -1.47
 35      PTTGC   59.00   59.50   58.00   59.25         0.00          0.00
 36      RATCH   56.00   56.25   55.00   56.00         0.00          0.00
 37      SAWAD   64.25   65.50   63.75   65.50         1.50          2.34
 38        SCB   90.50   91.00   89.25   90.25        -0.25         -0.28
 39        SCC  385.00  387.00  380.00  384.00        -2.00         -0.52
 40       SCGP   42.25   43.00   41.75   42.50         0.25          0.59
 41      TISCO   90.25   90.25   89.00   89.25        -1.00         -1.11
 42        TMB    1.20    1.20    1.17    1.18        -0.01         -0.84
 43        TOA   34.00   34.75   34.00   34.50         0.50          1.47
 44        TOP   54.00   55.25   53.75   54.75         0.50          0.92
 45       TRUE    3.66    3.70    3.52    3.58        -0.04         -1.10
 46        TTW   12.30   12.40   12.20   12.40         0.10          0.81
 47         TU   14.80   14.90   14.40   14.60        -0.20         -1.35
 48        VGI    7.35    7.60    7.30    7.60         0.20          2.70
 49        WHA    3.30    3.32    3.18    3.28         0.00          0.00

     เสนอซื้อ  เสนอขาย  ปริมาณ(หุ้น)  มูลค่า('000 บาท)
 0     187.50   188.00      13081285        2457807.74
 1      64.75    65.00      39718799        2594386.33
 2       5.05     5.10      83835993         425045.77
 3     124.50   125.00      15051923        1886404.86
 4      21.80    21.90      65753801        1437088.78
 5       9.05     9.10      43034566         390459.69
 6      51.25    51.50      12926042         661010.75
 7     120.00   120.50     170924170       18068263.19
 8      37.25    37.50      31374634        1157840.75
 9      17.10    17.20       3879670          66981.34
 10     10.40    10.50      59740189         621141.13
 11    113.50   114.00       4204526         477854.78
 12     61.75    62.00      56489498        3505653.04
 13     27.25    27.50      96820175        2641936.83
 14     53.00    53.25      18649895         992276.86
 15     35.25    35.50      16579418         579272.63
 16     35.25    35.50      18172308         643861.85
 17     46.75    47.00      14698303         686624.09
 18    205.00   206.00       3040898         627866.70
 19     18.40    18.50      16104104         296589.00
 20     70.50    70.75      12764535         895548.90
 21     35.50    35.75      31754191        1127758.50
 22     14.40    14.50      39405495         569722.25
 23     57.25    57.50      13058282         751459.07
 24      3.76     3.78     374519965        1410573.92
 25     37.50    37.75      40839706        1509235.88
 26    119.00   119.50      24853044        2963639.48
 27     11.70    11.80      53871746         633682.11
 28     55.50    55.75      16851188         932261.87
 29      8.60     8.65      94723998         812463.20
 30     26.75    27.00      51837013        1396898.89
 31     59.50    59.75      25860336        1531059.61
 32     37.75    38.00      14248875         541860.18
 33     42.50    42.75     139381554        5968561.03
 34    100.50   101.00      16398970        1651080.75
 35     59.00    59.25      27522595        1621294.51
 36     55.75    56.00       5777684         321966.91
 37     65.25    65.50      16564988        1075856.53
 38     90.00    90.25      19220903        1731600.52
 39    383.00   384.00       6494226        2487878.66
 40     42.25    42.50      36047686        1527133.06
 41     89.25    89.50       5862125         525060.97
 42      1.17     1.18     739294654         872191.24
 43     34.25    34.50       2306398          79111.07
 44     54.75    55.00      20060621        1094574.12
 45      3.56     3.58     413004958        1497106.76
 46     12.30    12.40       6819583          84218.72
 47     14.50    14.60      38737905         563993.12
 48      7.55     7.60      46662233         347055.31
 49      3.26     3.28     163673939         532702.91  ,
   Symbol Last Chg
 0      -    -   -
 1      -    -   -
 2      -    -   -,
 Empty DataFrame
 Columns: [Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3]
 Index: []]

In [6]:
df[0]

,Unnamed: 0,ล่าสุด,เปลี่ยน แปลง,%เปลี่ยน แปลง,สูงสุด,ต่ำสุด,ปริมาณ ('000 หุ้น),มูลค่า (ล้านบาท)
0,SET,1482.38,-1.51,-0.10,1489.78,1475.01,23061923,117095.61
1,SET50,947.28,-1.71,-0.18,953.60,940.86,3289303,77714.93
2,SET100,2116.85,-3.39,-0.16,2130.57,2103.80,5131122,92684.61
3,sSET,721.04,-1.61,-0.22,726.51,720.68,817414,3582.92
4,SETCLMV,970.42,-6.03,-0.62,979.68,965.81,2134929,56058.29
5,SETHD,1050.40,-4.11,-0.39,1058.45,1042.83,961085,25229.81
6,SETTHSI,929.59,-1.45,-0.16,933.75,923.17,3109019,58681.32
7,SETWB,911.12,-3.52,-0.38,919.17,905.25,862004,35821.50
8,mai,338.57,1.29,0.38,340.26,337.76,1139986,1868.10

# แบบที่ 2

In [7]:
import requests
import pandas as pd

In [8]:
url = 'https://www.settrade.com/C13_MarketSummary.jsp?detail=SET50'

In [9]:
web_data = requests.get(url)
web_data.encoding = 'tis-620'

In [10]:
df = pd.read_html(web_data.text)

In [11]:
len(df)

6

In [12]:
df

[  Unnamed: 0   ล่าสุด  เปลี่ยน  แปลง  %เปลี่ยน  แปลง   สูงสุด   ต่ำสุด  \
 0        SET  1482.38          -1.51           -0.10  1489.78  1475.01
 1      SET50   947.28          -1.71           -0.18   953.60   940.86
 2     SET100  2116.85          -3.39           -0.16  2130.57  2103.80
 3       sSET   721.04          -1.61           -0.22   726.51   720.68
 4    SETCLMV   970.42          -6.03           -0.62   979.68   965.81
 5      SETHD  1050.40          -4.11           -0.39  1058.45  1042.83
 6    SETTHSI   929.59          -1.45           -0.16   933.75   923.17
 7      SETWB   911.12          -3.52           -0.38   919.17   905.25
 8        mai   338.57           1.29            0.38   340.26   337.76

    ปริมาณ  ('000 หุ้น)  มูลค่า  (ล้านบาท)
 0             23061923          117095.61
 1              3289303           77714.93
 2              5131122           92684.61
 3               817414            3582.92
 4              2134929           56058.29
 5               961085           25229.81
 6              3109019           58681.32
 7               862004           35821.50
 8              1139986            1868.10  ,
        Unnamed: 0 หลักทรัพย์ * ปริมาณ  *('000 หุ้น)
 0       เพิ่มขึ้น          636              6495512
 1  ไม่เปลี่ยนแปลง          443              5009461
 2            ลดลง         1130             12179186
 3       สถานะตลาด       Closed               Closed,
               ค่าสถิติสำคัญและผลการดำเนินงาน
                           Unnamed: 0_level_1       SET     mai
 0  มูลค่าหลักทรัพย์ตามราคาตลาด. (พันล้านบาท)  16368.35  242.04
 1    อันตราหมุนเวียนปริมาณการซื้อขาย(YTD)(%)    212.28   56.32
 2                                 P/E (เท่า)     29.42   71.81
 3                                P/BV (เท่า)      1.67    1.77
 4                    อัตราเงินปันผลตอบแทน(%)      3.26    2.49,
    หลักทรัพย์    เปิด  สูงสุด  ต่ำสุด  ล่าสุด  เปลี่ยนแปลง  %เปลี่ยนแปลง  \
 0      ADVANC  189.50  190.50  187.00  187.50        -1.50         -0.79
 1         AOT   66.00   66.25   65.00   65.00        -1.00         -1.52
 2         AWC    5.10    5.15    5.00    5.10         0.00          0.00
 3         BBL  127.50  128.00  124.00  125.00        -3.50         -2.72
 4        BDMS   22.00   22.20   21.70   21.80        -0.30         -1.36
 5         BEM    9.05    9.10    9.00    9.10         0.05          0.55
 6       BGRIM   52.00   52.00   50.50   51.25        -0.75         -1.44
 7          BH  121.50  123.00  119.50  120.00        -2.50         -2.04
 8         BJC   37.50   37.75   36.75   37.50         0.00          0.00
 9         BPP   17.10   17.50   17.10   17.10        -0.10         -0.58
 10        BTS   10.40   10.50   10.20   10.50         0.20          1.94
 11        CBG  115.00  115.00  112.50  114.00        -0.50         -0.44
 12      CPALL   62.75   63.00   61.50   62.00        -0.50         -0.80
 13        CPF   27.25   27.75   26.75   27.50         0.00          0.00
 14        CPN   53.00   53.75   52.50   53.25        -0.25         -0.47
 15        CRC   34.75   35.25   34.25   35.25         0.50          1.44
 16       DTAC   36.00   36.50   34.75   35.25        -1.00         -2.76
 17         EA   45.75   47.25   45.75   47.00         1.25          2.73
 18       EGCO  210.00  211.00  204.00  206.00        -4.00         -1.90
 19     GLOBAL   18.40   18.60   18.20   18.40         0.00          0.00
 20       GPSC   70.50   71.00   69.50   70.50        -0.25         -0.35
 21       GULF   35.50   35.75   35.00   35.75         0.25          0.70
 22      HMPRO   14.30   14.60   14.30   14.50         0.20          1.40
 23     INTUCH   58.25   58.25   57.25   57.50        -0.50         -0.86
 24       IRPC    3.84    3.86    3.70    3.78        -0.06         -1.56
 25        IVL   36.50   37.75   36.00   37.75         1.00          2.72
 26      KBANK  120.00  121.00  118.50  119.00        -2.50         -2.06
 27        KTB   11.80   11.90   11.60   11.80        -0.10         -0.84
 28        KTC   55.00   56.00   54.50   55.75         1.00          1.83
 29         LH    8.45    8.65    8.45    8.65         0.15          1.76
 30       MINT   27.50   27.75   26.75   26.75        -0.75         -2.73
 31        MTC   57.50   60.00   57.00   59.75         2.50          4.37
 32        OSP   38.00   38.75   37.50   38.00         0.00          0.00
 33        PTT   42.75   43.25   42.50   42.75         0.50          1.18
 34      PTTEP  101.50  102.50  100.00  100.50        -1.50         -1.47
 35      PTTGC   59.00   59.50   58.00   59.25         0.00          0.00
 36      RATCH   56.00   56.25   55.00   56.00         0.00          0.00
 37      SAWAD   64.25   65.50   63.75   65.50         1.50          2.34
 38        SCB   90.50   91.00   89.25   90.25        -0.25         -0.28
 39        SCC  385.00  387.00  380.00  384.00        -2.00         -0.52
 40       SCGP   42.25   43.00   41.75   42.50         0.25          0.59
 41      TISCO   90.25   90.25   89.00   89.25        -1.00         -1.11
 42        TMB    1.20    1.20    1.17    1.18        -0.01         -0.84
 43        TOA   34.00   34.75   34.00   34.50         0.50          1.47
 44        TOP   54.00   55.25   53.75   54.75         0.50          0.92
 45       TRUE    3.66    3.70    3.52    3.58        -0.04         -1.10
 46        TTW   12.30   12.40   12.20   12.40         0.10          0.81
 47         TU   14.80   14.90   14.40   14.60        -0.20         -1.35
 48        VGI    7.35    7.60    7.30    7.60         0.20          2.70
 49        WHA    3.30    3.32    3.18    3.28         0.00          0.00

     เสนอซื้อ  เสนอขาย  ปริมาณ(หุ้น)  มูลค่า('000 บาท)
 0     187.50   188.00      13081285        2457807.74
 1      64.75    65.00      39718799        2594386.33
 2       5.05     5.10      83835993         425045.77
 3     124.50   125.00      15051923        1886404.86
 4      21.80    21.90      65753801        1437088.78
 5       9.05     9.10      43034566         390459.69
 6      51.25    51.50      12926042         661010.75
 7     120.00   120.50     170924170       18068263.19
 8      37.25    37.50      31374634        1157840.75
 9      17.10    17.20       3879670          66981.34
 10     10.40    10.50      59740189         621141.13
 11    113.50   114.00       4204526         477854.78
 12     61.75    62.00      56489498        3505653.04
 13     27.25    27.50      96820175        2641936.83
 14     53.00    53.25      18649895         992276.86
 15     35.25    35.50      16579418         579272.63
 16     35.25    35.50      18172308         643861.85
 17     46.75    47.00      14698303         686624.09
 18    205.00   206.00       3040898         627866.70
 19     18.40    18.50      16104104         296589.00
 20     70.50    70.75      12764535         895548.90
 21     35.50    35.75      31754191        1127758.50
 22     14.40    14.50      39405495         569722.25
 23     57.25    57.50      13058282         751459.07
 24      3.76     3.78     374519965        1410573.92
 25     37.50    37.75      40839706        1509235.88
 26    119.00   119.50      24853044        2963639.48
 27     11.70    11.80      53871746         633682.11
 28     55.50    55.75      16851188         932261.87
 29      8.60     8.65      94723998         812463.20
 30     26.75    27.00      51837013        1396898.89
 31     59.50    59.75      25860336        1531059.61
 32     37.75    38.00      14248875         541860.18
 33     42.50    42.75     139381554        5968561.03
 34    100.50   101.00      16398970        1651080.75
 35     59.00    59.25      27522595        1621294.51
 36     55.75    56.00       5777684         321966.91
 37     65.25    65.50      16564988        1075856.53
 38     90.00    90.25      19220903        1731600.52
 39    383.00   384.00       6494226        2487878.66
 40     42.25    42.50      36047686        1527133.06
 41     89.25    89.50       5862125         525060.97
 42      1.17     1.18     739294654         872191.24
 43     34.25    34.50       2306398          79111.07
 44     54.75    55.00      20060621        1094574.12
 45      3.56     3.58     413004958        1497106.76
 46     12.30    12.40       6819583          84218.72
 47     14.50    14.60      38737905         563993.12
 48      7.55     7.60      46662233         347055.31
 49      3.26     3.28     163673939         532702.91  ,
   Symbol Last Chg
 0      -    -   -
 1      -    -   -
 2      -    -   -,
 Empty DataFrame
 Columns: [Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3]
 Index: []]

In [13]:
df[0]

,Unnamed: 0,ล่าสุด,เปลี่ยน แปลง,%เปลี่ยน แปลง,สูงสุด,ต่ำสุด,ปริมาณ ('000 หุ้น),มูลค่า (ล้านบาท)
0,SET,1482.38,-1.51,-0.10,1489.78,1475.01,23061923,117095.61
1,SET50,947.28,-1.71,-0.18,953.60,940.86,3289303,77714.93
2,SET100,2116.85,-3.39,-0.16,2130.57,2103.80,5131122,92684.61
3,sSET,721.04,-1.61,-0.22,726.51,720.68,817414,3582.92
4,SETCLMV,970.42,-6.03,-0.62,979.68,965.81,2134929,56058.29
5,SETHD,1050.40,-4.11,-0.39,1058.45,1042.83,961085,25229.81
6,SETTHSI,929.59,-1.45,-0.16,933.75,923.17,3109019,58681.32
7,SETWB,911.12,-3.52,-0.38,919.17,905.25,862004,35821.50
8,mai,338.57,1.29,0.38,340.26,337.76,1139986,1868.10